import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ShieldAlert, Database, Plus, Edit2, Trash2, Calendar, Users, ShoppingBag, DollarSign, ToggleLeft, ToggleRight, Sparkles, AlertCircle, CheckCircle, Terminal, Clipboard, Loader2, ArrowLeft, Sun, Moon, Upload, Image, X } from 'lucide-react';
import { useTheme } from '../ThemeContext';
import { supabase } from '../supabaseClient';
import { MENU_ITEMS } from '../data/menu';
import { MenuItem } from '../types';

interface LiveRequest {
  id: number;
  created_at: string;
  customer_name: string;
  customer_phone: string;
  customer_address: string;
  cart_summary: string;
  status: string;
}

interface OrderRecord {
  id: number;
  created_at: string;
  customer_name: string;
  customer_phone: string;
  customer_address: string;
  items: string;
  total_price: number;
  status: string;
}

export default function AdminPortal({ onGoBack }: { onGoBack: () => void }) {
  const { isDark, toggleTheme } = useTheme();

  // Login credentials state
  const [adminId, setAdminId] = useState('');
  const [adminPass, setAdminPass] = useState('');
  const [isLoggedIn, setIsLoggedIn] = useState(() => {
    return sessionStorage.getItem('tbc_admin_auth') === 'true';
  });
  const [loginError, setLoginError] = useState('');

  // Active sub-tab: 'dashboard' | 'orders' | 'menu' | 'setup'
  const [activeTab, setActiveTab] = useState<'dashboard' | 'orders' | 'menu' | 'setup'>('dashboard');

  // Live Requests (Availability Approvals)
  const [liveRequests, setLiveRequests] = useState<LiveRequest[]>([]);
  const [isLiveLoading, setIsLiveLoading] = useState(false);

  // Orders and Calendar filtering
  const [selectedDate, setSelectedDate] = useState(() => {
    const today = new Date();
    return today.toISOString().split('T')[0];
  });
  const [orders, setOrders] = useState<OrderRecord[]>([]);
  const [isOrdersLoading, setIsOrdersLoading] = useState(false);

  // Menu items (from Supabase)
  const [supabaseMenu, setSupabaseMenu] = useState<MenuItem[]>([]);
  const [isMenuLoading, setIsMenuLoading] = useState(false);
  
  // Menu Item Editor modal / form state
  const [editingItem, setEditingItem] = useState<Partial<MenuItem> | null>(null);
  const [isMenuFormOpen, setIsMenuFormOpen] = useState(false);
  const [menuFormError, setMenuFormError] = useState('');
  const [isSubmittingMenu, setIsSubmittingMenu] = useState(false);

  // DB Setup states
  const [isSeeding, setIsSeeding] = useState(false);
  const [seedSuccess, setSeedSuccess] = useState(false);

  // Custom non-blocking notifications and drag-drop upload states
  const [adminNotification, setAdminNotification] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  const [itemToDelete, setItemToDelete] = useState<MenuItem | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const [showUrlInput, setShowUrlInput] = useState(false);

  // Auto dismiss notifications after 5 seconds
  useEffect(() => {
    if (adminNotification) {
      const timer = setTimeout(() => setAdminNotification(null), 5000);
      return () => clearTimeout(timer);
    }
  }, [adminNotification]);

  const sqlSnippet = `CREATE TABLE IF NOT EXISTS customers_tbc (
  phone TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  customer_phone TEXT NOT NULL,
  item_id TEXT NOT NULL,
  item_name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  quantity INTEGER NOT NULL,
  image TEXT,
  category TEXT
);

CREATE TABLE IF NOT EXISTS availability_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  cart_summary TEXT NOT NULL,
  status TEXT DEFAULT 'pending' NOT NULL
);

CREATE TABLE IF NOT EXISTS menu_items (
  id TEXT PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  description TEXT NOT NULL,
  image TEXT NOT NULL,
  is_veg BOOLEAN DEFAULT true NOT NULL,
  is_popular BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS orders_v2 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  items TEXT NOT NULL,
  total_price NUMERIC NOT NULL,
  status TEXT DEFAULT 'placed' NOT NULL
);

-- Row Level Security (RLS) Rules for general access
ALTER TABLE customers_tbc ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE availability_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders_v2 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select customers_tbc" ON customers_tbc FOR SELECT USING (true);
CREATE POLICY "Allow public insert customers_tbc" ON customers_tbc FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update customers_tbc" ON customers_tbc FOR UPDATE USING (true);

CREATE POLICY "Allow public select cart_items" ON cart_items FOR SELECT USING (true);
CREATE POLICY "Allow public insert cart_items" ON cart_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete cart_items" ON cart_items FOR DELETE USING (true);

CREATE POLICY "Allow public select availability_requests" ON availability_requests FOR SELECT USING (true);
CREATE POLICY "Allow public insert availability_requests" ON availability_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update availability_requests" ON availability_requests FOR UPDATE USING (true);

CREATE POLICY "Allow public select menu_items" ON menu_items FOR SELECT USING (true);
CREATE POLICY "Allow public insert menu_items" ON menu_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update menu_items" ON menu_items FOR UPDATE USING (true);
CREATE POLICY "Allow public delete menu_items" ON menu_items FOR DELETE USING (true);

CREATE POLICY "Allow public select orders_v2" ON orders_v2 FOR SELECT USING (true);
CREATE POLICY "Allow public insert orders_v2" ON orders_v2 FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update orders_v2" ON orders_v2 FOR UPDATE USING (true);`;

  // Handle Login submission
  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (adminId === 'tbcresturant' && adminPass === 'tbc@123') {
      setIsLoggedIn(true);
      sessionStorage.setItem('tbc_admin_auth', 'true');
      setLoginError('');
    } else {
      setLoginError('Invalid Admin ID or password credentials.');
    }
  };

  const handleLogout = () => {
    setIsLoggedIn(false);
    sessionStorage.removeItem('tbc_admin_auth');
  };

  const handleImageFile = (file: File) => {
    if (!file.type.startsWith('image/')) {
      setMenuFormError('Please drop/upload a valid image file.');
      return;
    }
    
    // limit size to 2MB to keep DB payloads healthy
    if (file.size > 2 * 1024 * 1024) {
      setMenuFormError('Image is too large. Please upload an image under 2MB.');
      return;
    }

    const reader = new FileReader();
    reader.onload = (event) => {
      if (event.target?.result) {
        setEditingItem(prev => prev ? { ...prev, image: event.target!.result as string } : null);
      }
    };
    reader.readAsDataURL(file);
  };

  // 1. Fetch pending live availability requests
  const fetchLiveRequests = async () => {
    setIsLiveLoading(true);
    try {
      const { data, error } = await supabase
        .from('availability_requests')
        .select('*')
        .eq('status', 'pending')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setLiveRequests(data || []);
    } catch (err) {
      console.error('Error fetching live availability requests:', err);
    } finally {
      setIsLiveLoading(false);
    }
  };

  // 2. Fetch orders placed on specific date
  const fetchOrdersByDate = async () => {
    setIsOrdersLoading(true);
    try {
      // Build start and end timestamps for the selected day in UTC
      const startDate = `${selectedDate}T00:00:00.000Z`;
      const endDate = `${selectedDate}T23:59:59.999Z`;

      const { data, error } = await supabase
        .from('orders_v2')
        .select('*')
        .gte('created_at', startDate)
        .lte('created_at', endDate)
        .order('created_at', { ascending: false });

      if (error) throw error;
      setOrders(data || []);
    } catch (err) {
      console.error('Error fetching orders:', err);
    } finally {
      setIsOrdersLoading(false);
    }
  };

  // 3. Fetch Menu from Supabase
  const fetchSupabaseMenu = async () => {
    setIsMenuLoading(true);
    try {
      const { data, error } = await supabase
        .from('menu_items')
        .select('*')
        .order('category', { ascending: true });

      if (error) throw error;
      
      const formatted = (data || []).map((item: any) => ({
        id: item.id,
        name: item.name,
        category: item.category,
        price: Number(item.price),
        description: item.description,
        image: item.image,
        isVeg: item.is_veg,
        isPopular: item.is_popular,
      }));
      
      setSupabaseMenu(formatted);
    } catch (err) {
      console.error('Error fetching menu_items:', err);
    } finally {
      setIsMenuLoading(false);
    }
  };

  // Poll live requests every 4 seconds in background when logged in and on dashboard tab
  useEffect(() => {
    if (!isLoggedIn || activeTab !== 'dashboard') return;
    
    fetchLiveRequests();
    const interval = setInterval(fetchLiveRequests, 4000);
    return () => clearInterval(interval);
  }, [isLoggedIn, activeTab]);

  // Refetch orders on selected date change
  useEffect(() => {
    if (isLoggedIn && activeTab === 'orders') {
      fetchOrdersByDate();
    }
  }, [isLoggedIn, activeTab, selectedDate]);

  // Refetch menu items on menu tab active
  useEffect(() => {
    if (isLoggedIn && activeTab === 'menu') {
      fetchSupabaseMenu();
    }
  }, [isLoggedIn, activeTab]);

  // Handle live request decision approval / rejection
  const handleRequestDecision = async (id: number, decision: 'approved' | 'rejected') => {
    try {
      const { error } = await supabase
        .from('availability_requests')
        .update({ status: decision })
        .eq('id', id);

      if (error) throw error;
      
      // Update local state instantly
      setLiveRequests(prev => prev.filter(r => r.id !== id));
      setAdminNotification({
        type: 'success',
        message: `Request successfully marked as ${decision}.`
      });
    } catch (err: any) {
      setAdminNotification({
        type: 'error',
        message: `Error updating request: ${err.message}`
      });
    }
  };

  // DB Seeder helper to insert all static MENU_ITEMS to Supabase menu_items table
  const handleSeedDatabase = async () => {
    setIsSeeding(true);
    setSeedSuccess(false);
    try {
      const formattedToInsert = MENU_ITEMS.map((item) => ({
        id: item.id,
        name: item.name,
        category: item.category,
        price: item.price,
        description: item.description,
        image: item.image,
        is_veg: item.isVeg,
        is_popular: !!item.isPopular,
      }));

      // Delete existing menu_items first to refresh clean
      await supabase.from('menu_items').delete().neq('id', 'placeholder_force_delete');

      // Bulk insert
      const { error } = await supabase
        .from('menu_items')
        .insert(formattedToInsert);

      if (error) throw error;

      setSeedSuccess(true);
      setAdminNotification({
        type: 'success',
        message: 'Menu items seeded successfully!'
      });
      if (activeTab === 'menu') fetchSupabaseMenu();
    } catch (err: any) {
      setAdminNotification({
        type: 'error',
        message: `Seeding failed. Please check if table "menu_items" is created. Error: ${err.message}`
      });
    } finally {
      setIsSeeding(false);
    }
  };

  // Create or Update Menu Item
  const handleSaveMenuItem = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingItem?.name || !editingItem?.category || !editingItem?.price || !editingItem?.description || !editingItem?.image) {
      setMenuFormError('Please fill in all details and provide/upload a dish image.');
      return;
    }

    setIsSubmittingMenu(true);
    setMenuFormError('');

    try {
      const payload = {
        name: editingItem.name,
        category: editingItem.category,
        price: Number(editingItem.price),
        description: editingItem.description,
        image: editingItem.image,
        is_veg: editingItem.isVeg ?? true,
        is_popular: editingItem.isPopular ?? false,
      };

      if (editingItem.id) {
        // Update existing
        const { error } = await supabase
          .from('menu_items')
          .update(payload)
          .eq('id', editingItem.id);

        if (error) throw error;
        setAdminNotification({
          type: 'success',
          message: `Dish "${editingItem.name}" updated successfully!`
        });
      } else {
        // Generate a random string ID
        const generatedId = `custom-${Date.now()}`;
        const { error } = await supabase
          .from('menu_items')
          .insert([{ ...payload, id: generatedId }]);

        if (error) throw error;
        setAdminNotification({
          type: 'success',
          message: `New dish "${editingItem.name}" added successfully!`
        });
      }

      setIsMenuFormOpen(false);
      setEditingItem(null);
      fetchSupabaseMenu();
    } catch (err: any) {
      setMenuFormError(err.message || 'Error saving menu item.');
    } finally {
      setIsSubmittingMenu(false);
    }
  };

  // Delete a Menu Item
  const handleDeleteMenuItem = (item: MenuItem) => {
    setItemToDelete(item);
  };

  const confirmDeleteMenuItem = async () => {
    if (!itemToDelete) return;
    setIsDeleting(true);
    try {
      const { error } = await supabase
        .from('menu_items')
        .delete()
        .eq('id', itemToDelete.id);

      if (error) throw error;
      setAdminNotification({
        type: 'success',
        message: `Dish "${itemToDelete.name}" deleted successfully!`
      });
      setItemToDelete(null);
      fetchSupabaseMenu();
    } catch (err: any) {
      setAdminNotification({
        type: 'error',
        message: `Delete failed: ${err.message}`
      });
    } finally {
      setIsDeleting(false);
    }
  };

  // Open modal to add menu item
  const handleAddNewItem = () => {
    setEditingItem({
      name: '',
      category: 'Appetizers',
      price: 0,
      description: '',
      image: '',
      isVeg: true,
      isPopular: false,
    });
    setMenuFormError('');
    setShowUrlInput(false);
    setIsMenuFormOpen(true);
  };

  // Copy SQL script to clipboard helper
  const handleCopySql = () => {
    navigator.clipboard.writeText(sqlSnippet);
    setAdminNotification({
      type: 'success',
      message: 'SQL Schema script copied to clipboard!'
    });
  };

  // Calculate daily order revenues
  const totalRevenue = orders.reduce((sum, o) => sum + Number(o.total_price), 0);

  return (
    <div className={`min-h-screen font-sans ${isDark ? 'bg-[#050505] text-white' : 'bg-zinc-50 text-zinc-950'}`}>
      
      {/* Header bar */}
      <header className={`border-b px-6 py-4 flex items-center justify-between ${
        isDark ? 'bg-[#080808] border-white/5' : 'bg-white border-zinc-200'
      }`}>
        <div className="flex items-center space-x-3">
          <button
            onClick={onGoBack}
            className={`p-2 rounded-lg cursor-pointer flex items-center justify-center transition-all ${
              isDark ? 'bg-white/5 text-zinc-400 hover:text-white' : 'bg-zinc-100 text-zinc-600 hover:text-zinc-900 shadow-sm'
            }`}
          >
            <ArrowLeft className="w-4 h-4" />
          </button>
          <div>
            <span className="text-[10px] uppercase tracking-widest font-mono text-[#ff4d00] font-bold">Secure Administrative Node</span>
            <h2 className="text-lg font-black tracking-wide font-sans">TBC BACKSTAGE PORTAL</h2>
          </div>
        </div>

        <div className="flex items-center space-x-3">
          <button
            onClick={toggleTheme}
            className={`p-2 rounded-lg border transition-all cursor-pointer ${
              isDark ? 'bg-zinc-900/80 border-zinc-850 text-amber-400' : 'bg-white border-zinc-200 text-indigo-600'
            }`}
          >
            {isDark ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
          </button>
          {isLoggedIn && (
            <button
              onClick={handleLogout}
              className="px-3.5 py-1.5 rounded-lg text-xs font-mono font-bold bg-rose-500/15 text-rose-500 hover:bg-rose-500/25 transition-all cursor-pointer"
            >
              Sign Out
            </button>
          )}
        </div>
      </header>

      {!isLoggedIn ? (
        /* Administrative Authentication Guard screen */
        <div className="max-w-md mx-auto mt-20 p-8 border rounded-3xl space-y-6" id="admin-login-screen">
          <div className="text-center space-y-2">
            <div className="inline-flex p-3 rounded-full bg-[#ff4d00]/10 border border-[#ff4d00]/25 text-[#ff4d00]">
              <ShieldAlert className="w-8 h-8 animate-pulse" />
            </div>
            <h3 className="text-xl font-black font-sans uppercase">Admin Authentication</h3>
            <p className={`text-xs ${isDark ? 'text-zinc-400' : 'text-zinc-650'}`}>
              Please enter official restaurant supervisor credentials to access Live Approvals, orders, and menu CRUD boards.
            </p>
          </div>

          <form onSubmit={handleLogin} className="space-y-4">
            <div>
              <label className="block text-[10px] font-mono uppercase tracking-wider mb-1 text-zinc-500">Admin Login ID</label>
              <input
                type="text"
                required
                placeholder="e.g. tbcresturant"
                value={adminId}
                onChange={(e) => setAdminId(e.target.value)}
                className={`w-full border focus:border-[#ff4d00]/50 font-sans text-sm rounded-xl px-4 py-2.5 focus:outline-none focus:ring-1 focus:ring-[#ff4d00]/20 transition-all ${
                  isDark
                    ? 'bg-zinc-950 border-white/5 text-white placeholder:text-zinc-800'
                    : 'bg-zinc-50 border-zinc-250 text-zinc-900'
                }`}
              />
            </div>

            <div>
              <label className="block text-[10px] font-mono uppercase tracking-wider mb-1 text-zinc-500">Secure Password</label>
              <input
                type="password"
                required
                placeholder="••••••••"
                value={adminPass}
                onChange={(e) => setAdminPass(e.target.value)}
                className={`w-full border focus:border-[#ff4d00]/50 font-sans text-sm rounded-xl px-4 py-2.5 focus:outline-none focus:ring-1 focus:ring-[#ff4d00]/20 transition-all ${
                  isDark
                    ? 'bg-zinc-950 border-white/5 text-white placeholder:text-zinc-800'
                    : 'bg-zinc-50 border-zinc-250 text-zinc-900'
                }`}
              />
            </div>

            {loginError && (
              <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-500 text-xs font-semibold">
                {loginError}
              </div>
            )}

            <button
              type="submit"
              className="w-full py-3.5 rounded-xl bg-[#ff4d00] hover:bg-[#ff6a00] text-sm font-black uppercase tracking-widest text-black shadow-lg"
            >
              Sign In Backstage
            </button>
          </form>

          <div className="border-t pt-4 text-center text-[10px] text-zinc-500 font-sans leading-relaxed">
            🔓 Password Tip: Use <strong className="text-zinc-400">tbcresturant</strong> and <strong className="text-zinc-400">tbc@123</strong> to enter.
          </div>
        </div>
      ) : (
        /* Logged In Dashboard Layout */
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 flex flex-col md:flex-row gap-8">
          
          {/* Backstage Tabs Menu Sidebar */}
          <div className="w-full md:w-64 shrink-0 space-y-3">
            <button
              onClick={() => setActiveTab('dashboard')}
              className={`w-full text-left py-3 px-4 rounded-xl text-xs font-bold uppercase tracking-wider font-sans border flex items-center justify-between transition-all cursor-pointer ${
                activeTab === 'dashboard'
                  ? 'bg-[#ff4d00] border-[#ff4d00] text-black shadow-lg'
                  : isDark
                    ? 'bg-zinc-950 border-white/5 text-zinc-400 hover:text-white hover:border-white/10'
                    : 'bg-white border-zinc-200 text-zinc-650 hover:bg-zinc-50'
              }`}
            >
              <span className="flex items-center gap-2">
                <Users className="w-4 h-4" /> Live Approval Feed
              </span>
              <span className={`px-2 py-0.5 rounded text-[10px] font-mono ${
                activeTab === 'dashboard' ? 'bg-black text-[#ff4d00]' : 'bg-red-500/20 text-red-500'
              }`}>
                {liveRequests.length}
              </span>
            </button>

            <button
              onClick={() => setActiveTab('orders')}
              className={`w-full text-left py-3 px-4 rounded-xl text-xs font-bold uppercase tracking-wider font-sans border flex items-center gap-2 transition-all cursor-pointer ${
                activeTab === 'orders'
                  ? 'bg-[#ff4d00] border-[#ff4d00] text-black shadow-lg'
                  : isDark
                    ? 'bg-zinc-950 border-white/5 text-zinc-400 hover:text-white hover:border-white/10'
                    : 'bg-white border-zinc-200 text-zinc-650 hover:bg-zinc-50'
              }`}
            >
              <Calendar className="w-4 h-4" /> Order Date Ledger
            </button>

            <button
              onClick={() => setActiveTab('menu')}
              className={`w-full text-left py-3 px-4 rounded-xl text-xs font-bold uppercase tracking-wider font-sans border flex items-center gap-2 transition-all cursor-pointer ${
                activeTab === 'menu'
                  ? 'bg-[#ff4d00] border-[#ff4d00] text-black shadow-lg'
                  : isDark
                    ? 'bg-zinc-950 border-white/5 text-zinc-400 hover:text-white hover:border-white/10'
                    : 'bg-white border-zinc-200 text-zinc-650 hover:bg-zinc-50'
              }`}
            >
              <ShoppingBag className="w-4 h-4" /> Menu Management
            </button>

            <button
              onClick={() => setActiveTab('setup')}
              className={`w-full text-left py-3 px-4 rounded-xl text-xs font-bold uppercase tracking-wider font-sans border flex items-center gap-2 transition-all cursor-pointer ${
                activeTab === 'setup'
                  ? 'bg-[#ff4d00] border-[#ff4d00] text-black shadow-lg'
                  : isDark
                    ? 'bg-zinc-950 border-white/5 text-zinc-400 hover:text-white hover:border-white/10'
                    : 'bg-white border-zinc-200 text-zinc-650 hover:bg-zinc-50'
              }`}
            >
              <Database className="w-4 h-4" /> Supabase DB Setup
            </button>
          </div>

          {/* Active Tab Main Container */}
          <div className="flex-grow space-y-6">
            
            {activeTab === 'dashboard' && (
              /* TAB 1: Live Availability Handler */
              <div className="space-y-6">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-xl font-black font-sans uppercase">Live Approval Feed</h3>
                    <p className={`text-xs ${isDark ? 'text-zinc-500' : 'text-zinc-450'}`}>
                      Incoming availability inquiries from active customer carts. Update status instantly.
                    </p>
                  </div>
                  <button
                    onClick={fetchLiveRequests}
                    disabled={isLiveLoading}
                    className={`p-2 rounded-xl disabled:opacity-50 cursor-pointer transition-all flex items-center justify-center ${
                      isDark ? 'bg-zinc-900 text-zinc-300' : 'bg-white border text-zinc-700 shadow-sm'
                    }`}
                  >
                    <Loader2 className={`w-4 h-4 ${isLiveLoading ? 'animate-spin' : ''}`} />
                  </button>
                </div>

                {liveRequests.length === 0 ? (
                  <div className={`p-12 border border-dashed rounded-3xl text-center space-y-4 ${
                    isDark ? 'border-white/5 bg-zinc-950/20' : 'border-zinc-200 bg-white shadow-sm'
                  }`}>
                    <CheckCircle className="w-10 h-10 text-emerald-500 mx-auto" />
                    <div>
                      <h4 className="text-sm font-bold font-sans">All Quiet Backstage</h4>
                      <p className="text-xs text-zinc-500 font-sans mt-1">
                        No active users are currently waiting for cart stock availability approvals.
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 gap-4" id="live-requests-feed">
                    {liveRequests.map((req) => (
                      <div
                        key={req.id}
                        className={`p-5 rounded-2xl border flex flex-col md:flex-row items-start md:items-center justify-between gap-4 transition-all ${
                          isDark ? 'bg-zinc-900/30 border-white/5' : 'bg-white border-zinc-200 shadow-md'
                        }`}
                      >
                        <div className="space-y-2 text-left">
                          <div className="flex flex-wrap gap-2 items-center">
                            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[#ff4d00]/10 text-[#ff4d00] border border-[#ff4d00]/20 font-bold uppercase">
                              Waiting Approval
                            </span>
                            <span className="text-[10px] text-zinc-500 font-mono">
                              Request ID: #{req.id}
                            </span>
                            <span className="text-[10px] text-zinc-550 font-mono">
                              {new Date(req.created_at).toLocaleTimeString()}
                            </span>
                          </div>

                          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs font-sans mt-1.5">
                            <div>
                              <strong className="text-[#ff4d00]">Customer Name:</strong>
                              <p className={isDark ? 'text-white' : 'text-zinc-800'}>{req.customer_name}</p>
                            </div>
                            <div>
                              <strong className="text-[#ff4d00]">Phone:</strong>
                              <p className={isDark ? 'text-white' : 'text-zinc-800'}>{req.customer_phone}</p>
                            </div>
                            <div>
                              <strong className="text-[#ff4d00]">Table/Delivery:</strong>
                              <p className={isDark ? 'text-white' : 'text-zinc-800'}>{req.customer_address}</p>
                            </div>
                          </div>

                          <div className={`mt-3 p-3 rounded-xl text-xs font-mono border leading-relaxed ${
                            isDark ? 'bg-zinc-950 border-white/5 text-zinc-300' : 'bg-zinc-50 border-zinc-200 text-zinc-700'
                          }`}>
                            <span className="text-zinc-500 font-semibold block uppercase text-[9px] mb-1">Cart Summary:</span>
                            {req.cart_summary}
                          </div>
                        </div>

                        {/* Action buttons */}
                        <div className="flex items-center gap-2 shrink-0 self-end md:self-center">
                          <button
                            onClick={() => handleRequestDecision(req.id, 'rejected')}
                            className="px-4 py-2 rounded-xl text-xs font-bold bg-rose-500/10 hover:bg-rose-500/20 text-rose-500 border border-rose-500/25 transition-all cursor-pointer"
                          >
                            Mark Unavailable (Reject)
                          </button>
                          <button
                            onClick={() => handleRequestDecision(req.id, 'approved')}
                            className="px-4 py-2 rounded-xl text-xs font-bold bg-emerald-500 hover:bg-emerald-600 text-black font-semibold transition-all cursor-pointer"
                          >
                            Mark Available (Approve)
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}

            {activeTab === 'orders' && (
              /* TAB 2: Date filtered orders ledger */
              <div className="space-y-6">
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                  <div>
                    <h3 className="text-xl font-black font-sans uppercase">Daily Order Ledger</h3>
                    <p className={`text-xs ${isDark ? 'text-zinc-500' : 'text-zinc-450'}`}>
                      Select specific date to retrieve total orders placed and compute dynamic revenues.
                    </p>
                  </div>
                  {/* Date Picker Input */}
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-mono font-bold text-zinc-500">Selected Date:</span>
                    <input
                      type="date"
                      value={selectedDate}
                      onChange={(e) => setSelectedDate(e.target.value)}
                      className={`px-3 py-2 border rounded-xl text-xs font-mono font-bold focus:outline-none focus:ring-1 focus:ring-[#ff4d00] ${
                        isDark ? 'bg-zinc-950 border-white/10 text-white' : 'bg-white border-zinc-250 text-zinc-900'
                      }`}
                    />
                  </div>
                </div>

                {/* Performance indicators */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <div className={`p-4 rounded-2xl border text-left ${
                    isDark ? 'bg-zinc-950/40 border-white/5' : 'bg-white border-zinc-200 shadow-sm'
                  }`}>
                    <span className="text-[10px] text-zinc-500 font-mono uppercase tracking-widest block">Total Placed Orders</span>
                    <span className="text-3xl font-black font-mono block mt-1">{orders.length}</span>
                  </div>

                  <div className={`p-4 rounded-2xl border text-left ${
                    isDark ? 'bg-zinc-950/40 border-white/5' : 'bg-white border-zinc-200 shadow-sm'
                  }`}>
                    <span className="text-[10px] text-zinc-500 font-mono uppercase tracking-widest block">Accumulated Revenue</span>
                    <span className="text-3xl font-black font-mono block mt-1 text-emerald-500">₹{totalRevenue}</span>
                  </div>

                  <div className={`p-4 rounded-2xl border text-left ${
                    isDark ? 'bg-zinc-950/40 border-white/5' : 'bg-white border-zinc-200 shadow-sm'
                  }`}>
                    <span className="text-[10px] text-zinc-500 font-mono uppercase tracking-widest block">Connection Status</span>
                    <span className="text-xs font-bold font-sans text-emerald-400 flex items-center gap-1.5 mt-2.5">
                      <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
                      Database Synced
                    </span>
                  </div>
                </div>

                {isOrdersLoading ? (
                  <div className="flex flex-col items-center justify-center py-16 space-y-3">
                    <Loader2 className="w-8 h-8 text-[#ff4d00] animate-spin" />
                    <p className="text-xs text-zinc-500 font-mono uppercase">Syncing date orders...</p>
                  </div>
                ) : orders.length === 0 ? (
                  <div className={`p-12 border border-dashed rounded-3xl text-center space-y-3 ${
                    isDark ? 'border-white/5 bg-zinc-950/10' : 'border-zinc-200 bg-white shadow-sm'
                  }`}>
                    <AlertCircle className="w-8 h-8 text-zinc-500 mx-auto" />
                    <h4 className="text-sm font-bold font-sans">No Orders Logged</h4>
                    <p className="text-xs text-zinc-500 max-w-sm mx-auto leading-relaxed">
                      We didn't locate any records in the <code>orders_v2</code> table for {selectedDate}.
                    </p>
                  </div>
                ) : (
                  <div className="space-y-4" id="ledger-orders-list">
                    {orders.map((ord) => (
                      <div
                        key={ord.id}
                        className={`p-5 rounded-2xl border text-left space-y-4 transition-all ${
                          isDark ? 'bg-zinc-900/30 border-white/5' : 'bg-white border-zinc-200 shadow-md'
                        }`}
                      >
                        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 border-b pb-3 border-zinc-850">
                          <div>
                            <span className="text-[9px] font-mono px-2 py-0.5 rounded bg-zinc-800 text-zinc-300 border border-zinc-700">
                              ORDER ID: #ORD-{ord.id}
                            </span>
                            <div className="text-xs font-mono text-zinc-500 mt-1">
                              Logged Time: {new Date(ord.created_at).toLocaleTimeString()}
                            </div>
                          </div>
                          <div className="text-right">
                            <span className="text-lg font-black text-emerald-500 font-mono block">
                              ₹{ord.total_price}
                            </span>
                          </div>
                        </div>

                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs font-sans">
                          <div className="space-y-2">
                            <span className="text-[10px] font-mono text-zinc-500 uppercase block">Customer Profile</span>
                            <div className="space-y-1">
                              <p className="font-bold">{ord.customer_name}</p>
                              <p className="text-zinc-500 font-mono">Phone: {ord.customer_phone}</p>
                              <p className="text-zinc-500">Address/Table: {ord.customer_address}</p>
                            </div>
                          </div>

                          <div className="space-y-2">
                            <span className="text-[10px] font-mono text-zinc-500 uppercase block">Ordered Items Summary</span>
                            <pre className="p-3 rounded-xl bg-zinc-950 text-zinc-300 font-mono text-xs overflow-x-auto border border-white/5 whitespace-pre-wrap leading-relaxed">
                              {ord.items}
                            </pre>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}

            {activeTab === 'menu' && (
              /* TAB 3: Menu CRUD panel */
              <div className="space-y-6">
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                  <div>
                    <h3 className="text-xl font-black font-sans uppercase">Menu Management</h3>
                    <p className={`text-xs ${isDark ? 'text-zinc-500' : 'text-zinc-450'}`}>
                      Add, delete, or update any dish directly inside the Supabase <code>menu_items</code> database.
                    </p>
                  </div>
                  <button
                    onClick={handleAddNewItem}
                    className="px-4 py-2.5 rounded-xl bg-[#ff4d00] hover:bg-[#ff6a00] text-xs font-black uppercase tracking-widest text-black flex items-center gap-1.5 shadow-lg shadow-[#ff4d00]/10 transition-all cursor-pointer"
                  >
                    <Plus className="w-4 h-4 text-black" /> Add New Dish
                  </button>
                </div>

                {isMenuLoading ? (
                  <div className="flex flex-col items-center justify-center py-16 space-y-3">
                    <Loader2 className="w-8 h-8 text-[#ff4d00] animate-spin" />
                    <p className="text-xs text-zinc-500 font-mono uppercase">Loading menu entries...</p>
                  </div>
                ) : supabaseMenu.length === 0 ? (
                  <div className={`p-12 border border-dashed rounded-3xl text-center space-y-4 ${
                    isDark ? 'border-white/5 bg-zinc-950/10' : 'border-zinc-200 bg-white shadow-sm'
                  }`}>
                    <AlertCircle className="w-8 h-8 text-zinc-500 mx-auto" />
                    <div>
                      <h4 className="text-sm font-bold font-sans">Menu Table Empty</h4>
                      <p className="text-xs text-zinc-500 max-w-sm mx-auto leading-relaxed mt-1">
                        We detected that your Supabase <code>menu_items</code> table is unseeded or missing columns.
                      </p>
                    </div>
                    <button
                      onClick={() => setActiveTab('setup')}
                      className="px-4 py-2 text-xs font-bold uppercase border rounded-xl hover:bg-[#ff4d00]/10 hover:border-[#ff4d00] transition-all text-[#ff4d00]"
                    >
                      Go Seed Menu Data
                    </button>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4" id="admin-menu-list">
                    {supabaseMenu.map((item) => (
                      <div
                        key={item.id}
                        className={`p-4 rounded-2xl border flex gap-3 transition-all ${
                          isDark ? 'bg-zinc-900/20 border-white/5' : 'bg-white border-zinc-200 shadow-sm'
                        }`}
                      >
                        <img
                          src={item.image}
                          alt={item.name}
                          className="w-16 h-16 rounded-xl object-cover shrink-0 bg-zinc-950 border border-white/5"
                        />
                        <div className="flex-grow text-left min-w-0 flex flex-col justify-between">
                          <div>
                            <div className="flex items-center justify-between gap-2">
                              <h4 className="text-sm font-black truncate">{item.name}</h4>
                              <span className="text-xs font-mono font-bold text-[#ff4d00] shrink-0">₹{item.price}</span>
                            </div>
                            <p className="text-[11px] text-zinc-500 line-clamp-1 mt-0.5">{item.description}</p>
                          </div>
                          
                          <div className="flex items-center justify-between border-t border-zinc-850 pt-2 mt-1">
                            <span className="text-[9px] font-mono uppercase text-zinc-500 bg-zinc-950 border border-white/5 px-2 py-0.5 rounded">
                              {item.category}
                            </span>
                            <div className="flex items-center gap-1">
                              <button
                                onClick={() => {
                                  setEditingItem(item);
                                  setMenuFormError('');
                                  setIsMenuFormOpen(true);
                                }}
                                className="p-1.5 rounded bg-amber-500/10 text-amber-500 hover:bg-amber-500 hover:text-black transition-all cursor-pointer"
                                title="Edit Item"
                              >
                                <Edit2 className="w-3.5 h-3.5" />
                              </button>
                              <button
                                onClick={() => handleDeleteMenuItem(item)}
                                className="p-1.5 rounded bg-rose-500/10 text-rose-500 hover:bg-rose-500 hover:text-white transition-all cursor-pointer"
                                title="Delete Item"
                              >
                                <Trash2 className="w-3.5 h-3.5" />
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}

            {activeTab === 'setup' && (
              /* TAB 4: Database configuration & seeder utility */
              <div className="space-y-6">
                <div>
                  <h3 className="text-xl font-black font-sans uppercase">Supabase Table Setup</h3>
                  <p className={`text-xs ${isDark ? 'text-zinc-500' : 'text-zinc-450'}`}>
                    Copy SQL scripts to create required structures in Supabase, and seed default menu entries.
                  </p>
                </div>

                <div className={`p-5 rounded-2xl border text-left space-y-4 ${
                  isDark ? 'bg-zinc-900/30 border-white/5' : 'bg-white border-zinc-200 shadow-md'
                }`}>
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-bold font-sans flex items-center gap-2">
                      <Terminal className="text-[#ff4d00] w-4.5 h-4.5" /> Supabase SQL Schema
                    </span>
                    <button
                      onClick={handleCopySql}
                      className="px-3 py-1.5 rounded bg-[#ff4d00]/10 hover:bg-[#ff4d00]/25 text-[#ff4d00] text-xs font-mono uppercase tracking-wider transition-all cursor-pointer"
                    >
                      Copy Schema Script
                    </button>
                  </div>
                  <pre className="p-4 rounded-xl bg-zinc-950 border border-white/5 text-[10px] font-mono text-zinc-300 max-h-64 overflow-y-auto leading-relaxed whitespace-pre">
                    {sqlSnippet}
                  </pre>
                  <p className="text-xs text-zinc-550 leading-relaxed">
                    💡 Paste this in the <strong>SQL Editor</strong> tab of your Supabase Workspace to create all 5 required tables and enable Row Level Security (RLS) rules.
                  </p>
                </div>

                {/* Auto seed menu helper */}
                <div className={`p-5 rounded-2xl border text-left flex flex-col sm:flex-row items-center justify-between gap-4 ${
                  isDark ? 'bg-zinc-900/30 border-white/5' : 'bg-white border-zinc-200 shadow-md'
                }`}>
                  <div className="space-y-1">
                    <h4 className="text-sm font-black flex items-center gap-1.5">
                      <Sparkles className="w-4 h-4 text-amber-400" /> Auto-Seed Static Menu Items
                    </h4>
                    <p className="text-xs text-zinc-500 max-w-lg">
                      TBC is equipped with 40+ default dishes (Appetizers, Mains, Momos, Soup, Rice, Pasta, Desserts). Seed them instantly to your live database.
                    </p>
                  </div>
                  <button
                    onClick={handleSeedDatabase}
                    disabled={isSeeding}
                    className="px-5 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-600 disabled:opacity-50 text-black font-black text-xs uppercase tracking-widest transition-all cursor-pointer shadow-lg shrink-0"
                  >
                    {isSeeding ? 'Seeding Tables...' : 'Seed Now'}
                  </button>
                </div>

                {seedSuccess && (
                  <div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center space-x-2.5 text-emerald-400">
                    <CheckCircle className="w-5 h-5" />
                    <span className="text-xs font-bold font-sans">Menu seeded successfully! Visit Menu Management tab.</span>
                  </div>
                )}
              </div>
            )}

          </div>
        </div>
      )}

      {/* Menu Item CRUD Form Modal overlay */}
      <AnimatePresence>
        {isMenuFormOpen && editingItem && (
          <div className="fixed inset-0 z-50 flex items-center justify-center px-4">
            <div className="absolute inset-0 bg-black/85 backdrop-blur-md" onClick={() => setIsMenuFormOpen(false)} />
            
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className={`relative w-full max-w-lg border rounded-3xl p-6 sm:p-8 overflow-hidden z-10 ${
                isDark ? 'bg-[#080808] border-white/10' : 'bg-white border-zinc-200 shadow-2xl'
              }`}
              id="menu-crud-modal"
            >
              <h3 className="text-lg font-black font-sans uppercase border-b pb-3 mb-4">
                {editingItem.id ? 'Edit Menu Item' : 'Add New Menu Item'}
              </h3>

              <form onSubmit={handleSaveMenuItem} className="space-y-4 text-left">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[10px] font-mono text-zinc-500 uppercase tracking-wider mb-1">Item Name</label>
                    <input
                      type="text"
                      required
                      placeholder="e.g. Garlic Naan"
                      value={editingItem.name || ''}
                      onChange={(e) => setEditingItem({ ...editingItem, name: e.target.value })}
                      className={`w-full border focus:border-[#ff4d00]/50 font-sans text-xs rounded-xl px-4 py-2.5 focus:outline-none ${
                        isDark ? 'bg-zinc-950 border-white/5 text-white' : 'bg-zinc-50 border-zinc-250 text-zinc-900'
                      }`}
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-mono text-zinc-500 uppercase tracking-wider mb-1">Price (₹)</label>
                    <input
                      type="number"
                      required
                      min={1}
                      placeholder="e.g. 50"
                      value={editingItem.price || 0}
                      onChange={(e) => setEditingItem({ ...editingItem, price: Number(e.target.value) })}
                      className={`w-full border focus:border-[#ff4d00]/50 font-sans text-xs rounded-xl px-4 py-2.5 focus:outline-none ${
                        isDark ? 'bg-zinc-950 border-white/5 text-white' : 'bg-zinc-50 border-zinc-250 text-zinc-900'
                      }`}
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-[10px] font-mono text-zinc-500 uppercase tracking-wider mb-1">Category</label>
                  <select
                    value={editingItem.category || 'Appetizers'}
                    onChange={(e) => setEditingItem({ ...editingItem, category: e.target.value })}
                    className={`w-full border focus:border-[#ff4d00]/50 font-sans text-xs rounded-xl px-4 py-2.5 focus:outline-none ${
                      isDark ? 'bg-zinc-950 border-white/5 text-white' : 'bg-zinc-50 border-zinc-250 text-zinc-900'
                    }`}
                  >
                    <option value="Appetizers">Appetizers</option>
                    <option value="Side Order / Momos">Side Order / Momos</option>
                    <option value="Soup">Soup</option>
                    <option value="Rice & Noodles">Rice & Noodles</option>
                    <option value="Roti & Breads">Roti & Breads</option>
                    <option value="Pasta & Maggie">Pasta & Maggie</option>
                    <option value="Main Course">Main Course</option>
                    <option value="Biryani">Biryani</option>
                  </select>
                </div>

                <div className="space-y-1">
                  <label className="block text-[10px] font-mono text-zinc-500 uppercase tracking-wider mb-1">
                    Dish Image (Drag & Drop or Click to Upload)
                  </label>
                  
                  <div
                    onDragOver={(e) => {
                      e.preventDefault();
                      setIsDragging(true);
                    }}
                    onDragLeave={() => setIsDragging(false)}
                    onDrop={(e) => {
                      e.preventDefault();
                      setIsDragging(false);
                      if (e.dataTransfer.files && e.dataTransfer.files[0]) {
                        handleImageFile(e.dataTransfer.files[0]);
                      }
                    }}
                    onClick={() => document.getElementById('dish-image-file')?.click()}
                    className={`border-2 border-dashed rounded-2xl p-6 text-center cursor-pointer transition-all duration-300 relative flex flex-col items-center justify-center space-y-2 ${
                      isDragging
                        ? 'border-[#ff4d00] bg-[#ff4d00]/5 scale-[0.99]'
                        : editingItem.image
                          ? 'border-emerald-500/40 bg-emerald-500/5'
                          : isDark
                            ? 'border-white/10 hover:border-white/20 bg-zinc-950'
                            : 'border-zinc-300 hover:border-zinc-400 bg-zinc-50'
                    }`}
                  >
                    <input
                      id="dish-image-file"
                      type="file"
                      accept="image/*"
                      className="hidden"
                      onChange={(e) => {
                        if (e.target.files && e.target.files[0]) {
                          handleImageFile(e.target.files[0]);
                        }
                      }}
                    />

                    {editingItem.image ? (
                      <div className="flex flex-col items-center space-y-2">
                        <div className="relative group w-28 h-20 rounded-xl overflow-hidden border border-white/10 shadow-md">
                          <img
                            src={editingItem.image}
                            alt="Preview"
                            className="w-full h-full object-cover"
                          />
                          <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-all">
                            <span className="text-[10px] text-white font-mono uppercase font-bold">Replace</span>
                          </div>
                        </div>
                        <span className="text-[10px] font-mono text-emerald-500 font-bold flex items-center gap-1">
                          <CheckCircle className="w-3.5 h-3.5" /> Image Ready
                        </span>
                      </div>
                    ) : (
                      <div className="space-y-1.5 py-2">
                        <Upload className={`w-8 h-8 mx-auto ${isDragging ? 'text-[#ff4d00] animate-bounce' : 'text-zinc-500'}`} />
                        <div className="text-xs">
                          <span className="font-bold text-[#ff4d00]">Click to upload</span> or drag and drop
                        </div>
                        <p className="text-[10px] text-zinc-500">Supports PNG, JPG, JPEG, WEBP (max 2MB)</p>
                      </div>
                    )}
                  </div>

                  <div className="pt-1.5 flex justify-between items-center">
                    <button
                      type="button"
                      onClick={() => setShowUrlInput(!showUrlInput)}
                      className="text-[10px] font-mono uppercase text-zinc-500 hover:text-[#ff4d00] transition-colors cursor-pointer"
                    >
                      {showUrlInput ? 'Hide URL Input' : 'Or Paste Image URL Instead'}
                    </button>
                    {editingItem.image && (
                      <button
                        type="button"
                        onClick={() => setEditingItem({ ...editingItem, image: '' })}
                        className="text-[10px] font-mono uppercase text-rose-500 hover:text-rose-400 transition-colors cursor-pointer"
                      >
                        Clear Image
                      </button>
                    )}
                  </div>

                  {showUrlInput && (
                    <motion.div
                      initial={{ opacity: 0, y: -5 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="mt-2"
                    >
                      <input
                        type="url"
                        placeholder="Paste image web address (https://...)"
                        value={editingItem.image || ''}
                        onChange={(e) => setEditingItem({ ...editingItem, image: e.target.value })}
                        className={`w-full border focus:border-[#ff4d00]/50 font-sans text-xs rounded-xl px-4 py-2 focus:outline-none ${
                          isDark ? 'bg-zinc-950 border-white/5 text-white' : 'bg-white border-zinc-250 text-zinc-900'
                        }`}
                      />
                    </motion.div>
                  )}
                </div>

                <div>
                  <label className="block text-[10px] font-mono text-zinc-500 uppercase tracking-wider mb-1">Description</label>
                  <textarea
                    required
                    rows={3}
                    placeholder="Short description of ingredients/portions"
                    value={editingItem.description || ''}
                    onChange={(e) => setEditingItem({ ...editingItem, description: e.target.value })}
                    className={`w-full border focus:border-[#ff4d00]/50 font-sans text-xs rounded-xl px-4 py-2.5 focus:outline-none ${
                      isDark ? 'bg-zinc-950 border-white/5 text-white' : 'bg-zinc-50 border-zinc-250 text-zinc-900'
                    }`}
                  />
                </div>

                <div className="flex items-center space-x-6 pt-2">
                  <label className="flex items-center space-x-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={editingItem.isVeg ?? true}
                      onChange={(e) => setEditingItem({ ...editingItem, isVeg: e.target.checked })}
                      className="rounded accent-emerald-500"
                    />
                    <span className="text-xs font-sans">Is Pure Veg</span>
                  </label>

                  <label className="flex items-center space-x-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={editingItem.isPopular ?? false}
                      onChange={(e) => setEditingItem({ ...editingItem, isPopular: e.target.checked })}
                      className="rounded accent-[#ff4d00]"
                    />
                    <span className="text-xs font-sans">Is Popular Dish</span>
                  </label>
                </div>

                {menuFormError && (
                  <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-500 text-xs font-semibold">
                    {menuFormError}
                  </div>
                )}

                <div className="flex justify-end gap-3 pt-4 border-t border-zinc-850">
                  <button
                    type="button"
                    onClick={() => setIsMenuFormOpen(false)}
                    className="px-4 py-2 rounded-xl text-xs font-bold bg-zinc-800 text-zinc-300 hover:bg-zinc-700 transition-all cursor-pointer"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={isSubmittingMenu}
                    className="px-5 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-600 disabled:opacity-50 text-black font-bold text-xs uppercase tracking-wider transition-all cursor-pointer"
                  >
                    {isSubmittingMenu ? 'Saving...' : 'Save Item'}
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Custom Delete Confirmation Modal */}
      <AnimatePresence>
        {itemToDelete && (
          <div className="fixed inset-0 z-50 flex items-center justify-center px-4">
            <div className="absolute inset-0 bg-black/85 backdrop-blur-md" onClick={() => setItemToDelete(null)} />
            
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className={`relative w-full max-w-sm border rounded-3xl p-6 overflow-hidden z-10 text-center space-y-4 ${
                isDark ? 'bg-[#080808] border-white/10' : 'bg-white border-zinc-200 shadow-2xl'
              }`}
              id="delete-confirm-modal"
            >
              <div className="mx-auto w-12 h-12 rounded-full bg-rose-500/10 text-rose-500 flex items-center justify-center">
                <Trash2 className="w-5 h-5" />
              </div>
              
              <div className="space-y-1.5">
                <h3 className="text-base font-black uppercase font-sans tracking-wide text-rose-500">Delete Menu Dish?</h3>
                <p className="text-xs text-zinc-500 max-w-xs mx-auto leading-relaxed font-sans">
                  Are you absolutely sure you want to permanently delete <strong className="text-rose-500">"{itemToDelete.name}"</strong>? This action is irreversible.
                </p>
              </div>

              <div className="flex gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setItemToDelete(null)}
                  className="flex-1 py-2.5 rounded-xl text-xs font-bold bg-zinc-800 text-zinc-300 hover:bg-zinc-700 transition-all cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={confirmDeleteMenuItem}
                  disabled={isDeleting}
                  className="flex-1 py-2.5 rounded-xl bg-rose-600 hover:bg-rose-550 disabled:opacity-50 text-white font-bold text-xs uppercase tracking-wider transition-all cursor-pointer flex items-center justify-center gap-1.5 shadow-lg shadow-rose-550/10"
                >
                  {isDeleting ? (
                    <>
                      <Loader2 className="w-3.5 h-3.5 animate-spin" /> Deleting...
                    </>
                  ) : (
                    'Confirm Delete'
                  )}
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Floating Notifications */}
      <AnimatePresence>
        {adminNotification && (
          <motion.div
            initial={{ opacity: 0, y: -50, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -20, scale: 0.95 }}
            className="fixed top-6 left-1/2 -translate-x-1/2 z-50 w-full max-w-sm px-4"
          >
            <div className={`p-4 rounded-2xl border shadow-xl flex items-start gap-3 backdrop-blur-md ${
              adminNotification.type === 'success'
                ? 'bg-emerald-950/90 border-emerald-500/30 text-emerald-300'
                : 'bg-rose-950/90 border-rose-500/30 text-rose-300'
            }`}>
              {adminNotification.type === 'success' ? (
                <CheckCircle className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
              ) : (
                <AlertCircle className="w-5 h-5 text-rose-400 shrink-0 mt-0.5" />
              )}
              <div className="flex-grow text-xs font-sans text-left leading-relaxed">
                {adminNotification.message}
              </div>
              <button
                onClick={() => setAdminNotification(null)}
                className="text-zinc-400 hover:text-white transition-colors cursor-pointer shrink-0"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

    </div>
  );
}
