import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, RefreshCw, Terminal, Check, Copy, ShoppingBag, Clock, Database, AlertCircle, Calendar } from 'lucide-react';
import { supabase } from '../supabaseClient';
import { useTheme } from '../ThemeContext';

interface Order {
  id: number | string;
  created_at: string;
  item_name: string;
  category: string;
  price: number;
  quantity: number;
  total_price: number;
  customer_name: string;
  customer_phone: string;
  delivery_details: string;
}

interface OrdersDrawerProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function OrdersDrawer({ isOpen, onClose }: OrdersDrawerProps) {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const { isDark } = useTheme();

  const sqlSnippet = `CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  item_name TEXT NOT NULL,
  category TEXT,
  price NUMERIC NOT NULL,
  quantity INTEGER NOT NULL,
  total_price NUMERIC NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT,
  delivery_details TEXT
);

-- Enable Row Level Security (RLS) but allow public inserts and reads
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select" ON orders FOR SELECT USING (true);`;

  const fetchOrders = async () => {
    setLoading(true);
    setErrorMsg(null);
    try {
      const { data, error } = await supabase
        .from('orders')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        throw error;
      }

      setOrders(data || []);
    } catch (err: any) {
      console.error('Error fetching orders:', err);
      setErrorMsg(err.message || 'Could not fetch orders from Supabase.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen) {
      fetchOrders();
    }
  }, [isOpen]);

  const handleCopySql = () => {
    navigator.clipboard.writeText(sqlSnippet);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 overflow-hidden" id="orders-drawer-root">
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/80 backdrop-blur-sm"
          />

          <div className="absolute inset-y-0 right-0 max-w-full flex pl-10">
            <motion.div
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 25, stiffness: 220 }}
              className={`w-screen max-w-md border-l shadow-2xl flex flex-col transition-colors duration-300 ${
                isDark 
                  ? 'bg-[#080808] border-white/5 text-white' 
                  : 'bg-white border-zinc-200 text-zinc-900'
              }`}
              id="orders-drawer-container"
            >
              {/* Header */}
              <div className={`p-6 border-b flex items-center justify-between transition-colors duration-300 ${
                isDark ? 'bg-zinc-950 border-white/5' : 'bg-zinc-50 border-zinc-200'
              }`}>
                <div className="flex items-center space-x-3">
                  <div className="p-2 rounded-xl bg-[#ff4d00]/10 border border-[#ff4d00]/20 text-[#ff4d00]">
                    <ShoppingBag className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className={`text-lg font-black tracking-wider uppercase font-sans ${
                      isDark ? 'text-white' : 'text-zinc-900'
                    }`}>
                      Order Ledger
                    </h3>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <button
                    onClick={fetchOrders}
                    disabled={loading}
                    className={`p-2 rounded-lg disabled:opacity-50 cursor-pointer transition-all ${
                      isDark 
                        ? 'bg-white/5 text-zinc-400 hover:text-white hover:bg-white/10' 
                        : 'bg-zinc-100 text-zinc-650 hover:text-zinc-950 hover:bg-zinc-200'
                    }`}
                    title="Refresh orders"
                  >
                    <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
                  </button>
                  <button
                    onClick={onClose}
                    className={`p-2 rounded-lg cursor-pointer transition-all ${
                      isDark 
                        ? 'bg-white/5 text-zinc-400 hover:text-white hover:bg-white/10' 
                        : 'bg-zinc-100 text-zinc-650 hover:text-zinc-950 hover:bg-zinc-200'
                    }`}
                    aria-label="Close panel"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Scrollable Content */}
              <div className="flex-1 overflow-y-auto p-6 space-y-6">
                {errorMsg ? (
                  /* Error View - Schema Helper */
                  <div className="space-y-4">
                    <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/20 flex gap-3 text-amber-500">
                      <AlertCircle className="w-5 h-5 shrink-0 mt-0.5 text-amber-600" />
                      <div>
                        <h4 className="text-xs font-bold uppercase tracking-wider font-sans text-amber-700">
                          Table Configuration Required
                        </h4>
                        <p className="text-xs text-zinc-600 font-sans mt-1 leading-relaxed">
                          We successfully reached Supabase, but the database table <code className="text-amber-700 font-mono bg-amber-100 px-1 py-0.5 rounded">orders</code> does not exist or has RLS restrictions.
                        </p>
                      </div>
                    </div>

                    <div className={`rounded-2xl border overflow-hidden transition-colors ${
                      isDark ? 'bg-zinc-950 border-white/5' : 'bg-zinc-50 border-zinc-200'
                    }`}>
                      <div className={`p-4 border-b flex items-center justify-between transition-colors ${
                        isDark ? 'border-white/5 bg-zinc-900/50' : 'border-zinc-200 bg-zinc-100/50'
                      }`}>
                        <div className="flex items-center space-x-2 text-zinc-500 font-mono text-xs">
                          <Terminal className="w-3.5 h-3.5" />
                          <span>SQL Setup Script</span>
                        </div>
                        <button
                          onClick={handleCopySql}
                          className="flex items-center space-x-1.5 px-3 py-1 rounded bg-[#ff4d00]/10 hover:bg-[#ff4d00]/20 text-[#ff4d00] text-[10px] font-bold font-sans uppercase tracking-wider transition-all cursor-pointer"
                        >
                          {copied ? (
                            <>
                              <Check className="w-3 h-3" />
                              <span>Copied!</span>
                            </>
                          ) : (
                            <>
                              <Copy className="w-3 h-3" />
                              <span>Copy Code</span>
                            </>
                          )}
                        </button>
                      </div>
                      <div className="p-4 overflow-x-auto max-h-60 text-[10px] font-mono text-zinc-300 bg-zinc-950 leading-relaxed">
                        <pre>{sqlSnippet}</pre>
                      </div>
                    </div>

                    <div className="text-center py-2">
                      <p className="text-[11px] text-zinc-500 font-sans leading-relaxed">
                        👉 Copy the script above and paste it directly into your <strong>Supabase SQL Editor</strong>, then press "Run" to establish the table structure!
                      </p>
                    </div>
                  </div>
                ) : loading ? (
                  /* Loading Spinner */
                  <div className="flex flex-col items-center justify-center py-20 space-y-3">
                    <RefreshCw className="w-8 h-8 text-[#ff4d00] animate-spin" />
                    <p className="text-xs text-zinc-500 font-mono uppercase tracking-widest">
                      Retrieving live orders...
                    </p>
                  </div>
                ) : orders.length === 0 ? (
                  /* Empty state */
                  <div className="text-center py-16 space-y-4">
                    <div className={`inline-flex items-center justify-center w-12 h-12 rounded-full border ${
                      isDark ? 'bg-zinc-900 border-white/5 text-zinc-600' : 'bg-zinc-50 border-zinc-200 text-zinc-400'
                    }`}>
                      <ShoppingBag className="w-6 h-6" />
                    </div>
                    <div>
                      <p className={`text-sm font-bold font-sans ${isDark ? 'text-zinc-400' : 'text-zinc-650'}`}>No Orders Placed Yet</p>
                      <p className="text-xs text-zinc-500 font-sans mt-1 max-w-[240px] mx-auto leading-relaxed">
                        Order some food from the menu above to test the real-time Supabase integration.
                      </p>
                    </div>
                  </div>
                ) : (
                  /* Order List */
                  <div className="space-y-4" id="orders-list">
                    {orders.map((order) => (
                      <div
                        key={order.id}
                        className={`p-4 rounded-2xl border transition-all space-y-4 ${
                          isDark 
                            ? 'bg-zinc-900/30 border-white/5 hover:border-white/10' 
                            : 'bg-zinc-50/50 border-zinc-200 hover:border-zinc-300'
                        }`}
                      >
                        {/* Order Header */}
                        <div className={`flex items-start justify-between border-b pb-3 ${
                          isDark ? 'border-white/5' : 'border-zinc-200'
                        }`}>
                          <div>
                            <span className={`text-[9px] font-mono uppercase tracking-widest px-2 py-0.5 rounded-full border ${
                              isDark 
                                ? 'bg-zinc-950 text-zinc-400 border-white/5' 
                                : 'bg-zinc-200/50 text-zinc-650 border-zinc-250'
                            }`}>
                              ID: #{order.id}
                            </span>
                            <h4 className={`text-xs font-bold font-sans mt-1.5 uppercase tracking-wide ${
                              isDark ? 'text-white' : 'text-zinc-900'
                            }`}>
                              {order.customer_name}
                            </h4>
                          </div>
                          <div className="text-right">
                            <span className="text-xs font-black text-[#ff4d00] font-mono block">
                              ₹{order.total_price}
                            </span>
                            <span className="text-[9px] text-zinc-550 font-mono flex items-center justify-end gap-1 mt-1">
                              <Calendar className="w-3 h-3 text-zinc-400" />
                              {new Date(order.created_at).toLocaleDateString(undefined, {
                                month: 'short',
                                day: 'numeric',
                                hour: '2-digit',
                                minute: '2-digit',
                              })}
                            </span>
                          </div>
                        </div>

                        {/* Order Details */}
                        <div className="grid grid-cols-2 gap-4 text-xs font-sans">
                          <div>
                            <span className={`text-[9px] font-mono uppercase tracking-wider block ${
                              isDark ? 'text-zinc-500' : 'text-zinc-450'
                            }`}>Ordered Item</span>
                            <p className={`font-semibold mt-0.5 ${isDark ? 'text-white' : 'text-zinc-900'}`}>{order.item_name}</p>
                            <span className="text-[10px] text-zinc-500 font-sans block mt-0.5">
                              Qty: {order.quantity} × ₹{order.price}
                            </span>
                          </div>
                          <div>
                            <span className={`text-[9px] font-mono uppercase tracking-wider block ${
                              isDark ? 'text-zinc-500' : 'text-zinc-450'
                            }`}>Details / Contact</span>
                            <p className={`font-semibold mt-0.5 truncate ${isDark ? 'text-zinc-300' : 'text-zinc-700'}`}>{order.delivery_details || 'N/A'}</p>
                            {order.customer_phone && (
                              <span className="text-[10px] text-zinc-500 font-mono block mt-0.5">
                                Phone: {order.customer_phone}
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </motion.div>
          </div>
        </div>
      )}
    </AnimatePresence>
  );
}
